### ISSUE TITLE
Failed to connect to Twitch API

### ISSUE THREAD

**Issue by michaelrath-fw** [anxdpanic/script.module.python.twitch#128]
Hi, two days ago the plugin suddenly stopped working.
It tells me, that it could no longer connect to the twitch API.

What are the required keys to enter in the Settings dialog?

Within the the twitch console (https://dev.twitch.tv/console) I created an App ('kodi') and entered the created Client ID and Client Secret in the `Private API Credentials` Part in the settings (i.e. `OAuth Client ID` and `OAuth Token`) od the twitch addon Settings UI.
Than I generated an OAuth Token (first entry in the settings) via the link [https://twitchaddon.page.link/oeJG]()

However, the plugin no longer works.
I see all my channels etc, but as soon as I want to view on, I get a 400 HTTP error (Invalid client header).
What am I missing?

* Add-on Version: 2.6.0
* Kodi Version:18.9.0
* Kodi GUI Language: English
* Operating System: raspberry pi
* Operating System Language: English

**Comment by anxdpanic** [comment]
The generated oauth token goes in the first setting on the Login page.
For the other see: https://github.com/anxdpanic/plugin.video.twitch/wiki/Private-API-Credentials---OAuth-Token
