### ISSUE TITLE
Get OAuth toke not working

### ISSUE THREAD

**Issue by CurtisLeeBolin** [anxdpanic/script.module.python.twitch#134]
I click `Get OAuth token`.
I am given this URL:

```
https://twitchaddon.page.link/Z1iP
```

When I browse to that URL and am redirected to this URL:

```
https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=ps2ed9zlj8zyqztsdz2tl4uys84b8k&redirect_uri=https://anxdpanic.github.io/plugin.video.twitch/token/&scope=user:read:follows+user:edit:follows+user:read:subscriptions+chat:read+chat:edit&force_verify=false&state
```

This page only has the word `Gone` on it.

**Comment by MrSprigster** [comment]
URL will be updated in a future release.  For now use:  https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=ps2ed9zlj8zyqztsdz2tl4uys84b8k&redirect_uri=https://anxdpanic.github.io/plugin.video.twitch/token/&scope=user:read:follows+user:edit:follows+user:read:subscriptions+chat:read+chat:edit&force_verify=false&state
